//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC8amKings.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EmployeeModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpNameField;
        
        private int EmpSalaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmpId {
            get {
                return this.EmpIdField;
            }
            set {
                if ((this.EmpIdField.Equals(value) != true)) {
                    this.EmpIdField = value;
                    this.RaisePropertyChanged("EmpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmpName {
            get {
                return this.EmpNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpNameField, value) != true)) {
                    this.EmpNameField = value;
                    this.RaisePropertyChanged("EmpName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmpSalary {
            get {
                return this.EmpSalaryField;
            }
            set {
                if ((this.EmpSalaryField.Equals(value) != true)) {
                    this.EmpSalaryField = value;
                    this.RaisePropertyChanged("EmpSalary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.EmployeeDetailServiceSoap")]
    public interface EmployeeDetailServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MVC8amKings.ServiceReference1.HelloWorldResponse HelloWorld(MVC8amKings.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MVC8amKings.ServiceReference1.HelloWorldResponse> HelloWorldAsync(MVC8amKings.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name getEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmployees", ReplyAction="*")]
        MVC8amKings.ServiceReference1.getEmployeesResponse getEmployees(MVC8amKings.ServiceReference1.getEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<MVC8amKings.ServiceReference1.getEmployeesResponse> getEmployeesAsync(MVC8amKings.ServiceReference1.getEmployeesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MVC8amKings.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MVC8amKings.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC8amKings.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MVC8amKings.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEmployees", Namespace="http://tempuri.org/", Order=0)]
        public MVC8amKings.ServiceReference1.getEmployeesRequestBody Body;
        
        public getEmployeesRequest() {
        }
        
        public getEmployeesRequest(MVC8amKings.ServiceReference1.getEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getEmployeesRequestBody {
        
        public getEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC8amKings.ServiceReference1.getEmployeesResponseBody Body;
        
        public getEmployeesResponse() {
        }
        
        public getEmployeesResponse(MVC8amKings.ServiceReference1.getEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVC8amKings.ServiceReference1.EmployeeModel[] getEmployeesResult;
        
        public getEmployeesResponseBody() {
        }
        
        public getEmployeesResponseBody(MVC8amKings.ServiceReference1.EmployeeModel[] getEmployeesResult) {
            this.getEmployeesResult = getEmployeesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeDetailServiceSoapChannel : MVC8amKings.ServiceReference1.EmployeeDetailServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeDetailServiceSoapClient : System.ServiceModel.ClientBase<MVC8amKings.ServiceReference1.EmployeeDetailServiceSoap>, MVC8amKings.ServiceReference1.EmployeeDetailServiceSoap {
        
        public EmployeeDetailServiceSoapClient() {
        }
        
        public EmployeeDetailServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeDetailServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeDetailServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeDetailServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC8amKings.ServiceReference1.HelloWorldResponse MVC8amKings.ServiceReference1.EmployeeDetailServiceSoap.HelloWorld(MVC8amKings.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MVC8amKings.ServiceReference1.HelloWorldRequest inValue = new MVC8amKings.ServiceReference1.HelloWorldRequest();
            inValue.Body = new MVC8amKings.ServiceReference1.HelloWorldRequestBody();
            MVC8amKings.ServiceReference1.HelloWorldResponse retVal = ((MVC8amKings.ServiceReference1.EmployeeDetailServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVC8amKings.ServiceReference1.HelloWorldResponse> MVC8amKings.ServiceReference1.EmployeeDetailServiceSoap.HelloWorldAsync(MVC8amKings.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVC8amKings.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            MVC8amKings.ServiceReference1.HelloWorldRequest inValue = new MVC8amKings.ServiceReference1.HelloWorldRequest();
            inValue.Body = new MVC8amKings.ServiceReference1.HelloWorldRequestBody();
            return ((MVC8amKings.ServiceReference1.EmployeeDetailServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC8amKings.ServiceReference1.getEmployeesResponse MVC8amKings.ServiceReference1.EmployeeDetailServiceSoap.getEmployees(MVC8amKings.ServiceReference1.getEmployeesRequest request) {
            return base.Channel.getEmployees(request);
        }
        
        public MVC8amKings.ServiceReference1.EmployeeModel[] getEmployees() {
            MVC8amKings.ServiceReference1.getEmployeesRequest inValue = new MVC8amKings.ServiceReference1.getEmployeesRequest();
            inValue.Body = new MVC8amKings.ServiceReference1.getEmployeesRequestBody();
            MVC8amKings.ServiceReference1.getEmployeesResponse retVal = ((MVC8amKings.ServiceReference1.EmployeeDetailServiceSoap)(this)).getEmployees(inValue);
            return retVal.Body.getEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVC8amKings.ServiceReference1.getEmployeesResponse> MVC8amKings.ServiceReference1.EmployeeDetailServiceSoap.getEmployeesAsync(MVC8amKings.ServiceReference1.getEmployeesRequest request) {
            return base.Channel.getEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVC8amKings.ServiceReference1.getEmployeesResponse> getEmployeesAsync() {
            MVC8amKings.ServiceReference1.getEmployeesRequest inValue = new MVC8amKings.ServiceReference1.getEmployeesRequest();
            inValue.Body = new MVC8amKings.ServiceReference1.getEmployeesRequestBody();
            return ((MVC8amKings.ServiceReference1.EmployeeDetailServiceSoap)(this)).getEmployeesAsync(inValue);
        }
    }
}
